name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          aws s3 sync --delete --region ap-northeast-1 ./files/ s3://demo-cloudfront-tammy-61/files
          aws s3 sync --delete --region ap-northeast-1 ./files/ s3://demo-cloudfront-tammy-61/files2
