name: Actions Workflow

on:
  push:
    branches:
      - master

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files_ignore: |
            *.yml
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "aws s3 sync --exact-timestamps --region ap-northeast-1 ./$file s3://demo-cloudfront-tammy-61/"
            aws s3 sync --exact-timestamps --region ap-northeast-1 "$file" s3://demo-cloudfront-tammy-61
          done
